[features]
seeds = false
[programs.localnet]
counter = "F48dBMHg9auQacc51avYooqu6JvWmoBY3WR5GZyUQT17"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/soldev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
